### ISSUE TITLE
index out of range exception reading Adam trophy nut

### ISSUE THREAD

**Issue by ScanMountGoat** [jam1garner/Smash-Forge#261]
The texture has never loaded correctly, but now it throws an exception.

[c00.zip](https://github.com/jam1garner/Smash-Forge/files/2280494/c00.zip)

First Broken Commit: 
e6f873209c06e1c51c48bca24070f248b59e524d

Stack Trace:

```   at Smash_Forge.GTX.swizzleSurface(GX2Surface surface, Boolean isCompressed)
   at Smash_Forge.GTX.swizzleBC(Byte[] data, Int32 width, Int32 height, Int32 format, Int32 tileMode, Int32 pitch, Int32 swizzle)
   at Smash_Forge.NUT.ReadNTWU(FileData d)
   at Smash_Forge.NUT.Read(FileData d)
   at Smash_Forge.NUT.Read(String filename)
   at Smash_Forge.NUT..ctor(String filename)
   at Smash_Forge.MainForm.OpenNut(String fileName, ModelContainer modelContainer)
   at Smash_Forge.MainForm.OpenNud(String pathNud, String viewportTitle, ModelViewport mvp)
   at Smash_Forge.MainForm.openFile(String fileName)
   at Smash_Forge.MainForm.openFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at Smash_Forge.Program.Main()
```

**Comment by ScanMountGoat** [comment]
fixed
