### ISSUE TITLE
[Melee Dat] TyMnDisp.dat null reference exception when creating render meshes

### ISSUE THREAD

**Issue by ScanMountGoat** [jam1garner/Smash-Forge#303]
Error: `System.NullReferenceException`

https://github.com/jam1garner/Smash-Forge/blob/55b5b07c3e4dabcc2f48f057bf0249c915c653cc/Smash%20Forge/Filetypes/Melee/MeleeDataObjectNode.cs#L388

**Comment by ScanMountGoat** [comment]
Stack Trace:
```
   at MeleeLib.IO.DATReader.Float()
   at MeleeLib.DAT.Helpers.GXVertexDecompressor.read3(DATReader d, GXCompType type, Int32 size)
   at MeleeLib.DAT.Helpers.GXVertexDecompressor.GetFormattedVertices(GXDisplayList dl, DatPolygon poly)
   at Smash_Forge.MeleeDataObjectNode.AddVertexContainer(GXVertexDecompressor decom, List`1 vertexContainers, DatPolygon polygon, GXDisplayList displayList) in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\Filetypes\Melee\MeleeDataObjectNode.cs:line 388
   at Smash_Forge.MeleeDataObjectNode.RefreshRenderMeshes() in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\Filetypes\Melee\MeleeDataObjectNode.cs:line 369
   at Smash_Forge.MeleeDataObjectNode.RefreshRendering() in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\Filetypes\Melee\MeleeDataObjectNode.cs:line 354
   at Smash_Forge.MeleeRootNode.RefreshDisplay() in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\Filetypes\Melee\MeleeRootNode.cs:line 228
   at Smash_Forge.MeleeDataNode.RefreshDisplay() in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\Filetypes\Melee\MeleeData.cs:line 200
   at Smash_Forge.MeleeDataNode.Render(Camera c) in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\Filetypes\Melee\MeleeData.cs:line 222
   at Smash_Forge.ModelViewport.DrawModels(Boolean drawShadow) in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\GUI\ModelViewport.cs:line 1830
   at Smash_Forge.ModelViewport.DrawModelsNormally(Int32 width, Int32 height, Int32 defaultFbo) in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\GUI\ModelViewport.cs:line 1764
   at Smash_Forge.ModelViewport.Render(Object sender, PaintEventArgs e, Int32 width, Int32 height, Int32 defaultFbo) in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\GUI\ModelViewport.cs:line 1737
   at Smash_Forge.ModelViewport.glViewport_Paint(Object sender, PaintEventArgs e) in C:\Users\Jonathan\Documents\GITHUB\Smash-Forge\Smash Forge\GUI\ModelViewport.cs:line 2183
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at OpenTK.GLControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
