### ISSUE TITLE
Bones spit out NullReferenceException save for VBN, PACs no go

### ISSUE THREAD

**Issue by TabuuForteAkugun** [jam1garner/Smash-Forge#6]
Specs:

Win 8/8,1
Date: 11/10/2016
NET: 4,5.2.

Error dump

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at VBN_Editor.OMO.read(FileData d, VBN v)
   at VBN_Editor.MainForm.importToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Ploaj** [comment]
Is this when saving the vbn or...?

**Comment by TabuuForteAkugun** [comment]
Nope, it was right on importing a file that was NOT a VBN (MDL0 and SMD)

**Comment by Ploaj** [comment]
The error message implies an animation. Did you already have an animation open?

**Comment by TabuuForteAkugun** [comment]
I had no animations open.

**Comment by Ploaj** [comment]
Try it with the newest build. If you are trying to open an animated smd for bones, then it may not work correctly.

**Comment by TabuuForteAkugun** [comment]
No, it was just a MDL0. And my SMD had no animations and still spit out this error.

**Comment by jam1garner** [comment]
do you still have this issue?

**Comment by TabuuForteAkugun** [comment]
No, I don't, It may be closed,.
