### ISSUE TITLE
Attempting to load certian .dat files give me an exception and don't load

### ISSUE THREAD

**Issue by fm360** [jam1garner/Smash-Forge#61]
I tried to load some .dat files into smash forge. Some of them work, but others end up giving me an "Index was outside the bounds of the array" exception.

Here is the error log:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Smash_Forge.FileData.readInt()
   at Smash_Forge.DAT.POBJ.Read(FileData d, DAT dat, DOBJ dobj, TreeNode parent)
   at Smash_Forge.DAT.DOBJ.Read(FileData d, DAT dat, TreeNode parent)
   at Smash_Forge.DAT.JOBJ.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.JOBJ.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.JOBJ.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.JOBJ.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.JOBJ.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.JOBJ.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.Map_Head.Head_Node.Head_Node_Object.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.Map_Head.Head_Node.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.Map_Head.Read(FileData d, DAT dat, TreeNode parentNode)
   at Smash_Forge.DAT.Read(FileData d)
   at Smash_Forge.MainForm.openFile(String filename)
   at Smash_Forge.MainForm.openFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Smash Forge
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mahdavib5791/Desktop/Smash-Forge-Latest_Commit%20(1)/updater/currentRelease/Smash%20Forge.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Users/mahdavib5791/Desktop/Smash-Forge-Latest_Commit%20(1)/updater/currentRelease/lib/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1664.6217
    CodeBase: file:///C:/Users/mahdavib5791/Desktop/Smash-Forge-Latest_Commit%20(1)/updater/currentRelease/lib/OpenTK.DLL
----------------------------------------
SALT
    Assembly Version: 1.2.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mahdavib5791/Desktop/Smash-Forge-Latest_Commit%20(1)/updater/currentRelease/lib/SALT.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1664.6217
    CodeBase: file:///C:/Users/mahdavib5791/Desktop/Smash-Forge-Latest_Commit%20(1)/updater/currentRelease/lib/OpenTK.GLControl.DLL
----------------------------------------
Octokit
    Assembly Version: 0.23.0.0
    Win32 Version: 0.23.0
    CodeBase: file:///C:/Users/mahdavib5791/Desktop/Smash-Forge-Latest_Commit%20(1)/updater/currentRelease/lib/Octokit.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by revel8n** [comment]
Need more information:
- Which dat file(s) were you trying to load?
- Is this with a version before of after my recent changes?

**Comment by Demonslayerx8** [comment]
with ur latest fixes to DAT's, stage meshes will not show anything at all.

**Comment by revel8n** [comment]
My fixes actually allowed more stages to load, but ultiimately i need to know which files you have troubles with to better address any issues.

On that note though, i have checked in my latest changes in this area, so hopefully that will help the rest of the stages to load now once they are merged in.

**Comment by fm360** [comment]
I have trouble with some stage files
